#!/usr/bin/env bash

set -eu

cargo build --release
./target/release/chambray --samples 128 -w 1080 -h 720 image.ppm

if [[ "$(uname)" == 'Darwin' ]];
then
	open image.ppm &
else
	gnome-open image.ppm &
fi

